name: Actions Trigger

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Print environment
        run: echo "Running in ${{ github.event.inputs.environment }} environment"

      - name: Compile Java project
        run: mvn compile

      - name: Copy dependencies
        run: mvn dependency:copy-dependencies

      - name: Run CompaniesTest
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITHUB_ENVIRONMENT: ${{ github.event.inputs.environment }}
        run: java -cp "target/classes:target/dependency/*" com.CompaniesTest

      - name: Upload results CSV
        uses: actions/upload-artifact@v4
        with:
          name: permanently_closed_notes
          path: permanently_closed_notes.csv
